/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Internal;

import App.controller.Class_Controller;
import App.controller.Course_Controller;
import App.controller.Student_Controller;
import App.model.tbl_Class;
import App.model.tbl_Course;
import App.model.tbl_Student;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC Hoang Anh
 */
public class Edit_Student extends javax.swing.JInternalFrame {

    /**
     * Creates new form Edit_Student
     */
    Connection conn;
    tbl_Student student;
    int id_teach;
    int role;

    List<tbl_Class> LClass;

    public interface reload {

        public void load_table();
    };

    reload load;

    public Edit_Student(Connection conn, tbl_Student student, int id_teach, int role, reload load) {
        this.conn = conn;
        this.student = student;
        this.id_teach = id_teach;
        this.role = role;
        this.load = load;
        initComponents();
        if (role == 1 || role == 2) {
            get_Class("");
        } else {
            get_Class(" where Course_ID = ( select Course_ID from tbl_Class where ID = " + student.getClass_ID() + " ) AND Teacher_ID = " + id_teach);
        }
        set_Class();
        loadform();
    }

    private void get_Class(String check) {
        Class_Controller CC = new Class_Controller(conn);
        LClass = CC.select(check);
    }

    private void set_Class() {
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        for (tbl_Class c : LClass) {
            dcbm.addElement(c.getName());
        }
        Class_Student.setModel(dcbm);
        for (int i = 0; i < LClass.size(); i++) {
            tbl_Class c = LClass.get(i);
            if (c.getId() == student.getClass_ID()) {
                Class_Student.setSelectedIndex(i);
            }
        }
    }

    private void loadform() {
        Roll.setText(student.getRoll());
        Name.setText(student.getName());
        Phone.setText(student.getPhone());
        Email.setText(student.getEmail());
        Address.setText(student.getAddress());
        try {
            DOB.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(student.getDOB()));
        } catch (ParseException ex) {
            Logger.getLogger(Edit_Student.class.getName()).log(Level.SEVERE, null, ex);
        }
        switch (student.getGender()) {
            case 1:
                Nam.doClick();
                break;
            case 2:
                Nu.doClick();
                break;
            default:
                unisex.doClick();
                break;
        }
        if (student.getStatus() == 1) {
            now.doClick();
        } else {
            unow.doClick();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        Roll = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        unisex = new javax.swing.JRadioButton();
        Nam = new javax.swing.JRadioButton();
        Nu = new javax.swing.JRadioButton();
        Class_Student = new javax.swing.JComboBox<>();
        now = new javax.swing.JRadioButton();
        unow = new javax.swing.JRadioButton();
        DOB = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Thông tin sinh viên");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel1.setText("MSSV");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel2.setText("Họ Tên");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel4.setText("SĐT");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel5.setText("Địa Chỉ");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel7.setText("Ngày Sinh");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel8.setText("Giới Tính");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel9.setText("Lớp");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel10.setText("Tình Trạng");

        Phone.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        Roll.setEditable(false);
        Roll.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        Name.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        Email.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        Address.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        buttonGroup1.add(unisex);
        unisex.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        unisex.setText("Khác");

        buttonGroup1.add(Nam);
        Nam.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Nam.setText("Nam");

        buttonGroup1.add(Nu);
        Nu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Nu.setText("Nữ");

        Class_Student.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Class_Student.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup2.add(now);
        now.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        now.setText("Đang học");

        buttonGroup2.add(unow);
        unow.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        unow.setText("Ra trường");

        DOB.setDateFormatString("dd/MM/yyyy");
        DOB.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton1.setText("Cập Nhật");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(Nam)
                                        .addGap(26, 26, 26)
                                        .addComponent(Nu)
                                        .addGap(36, 36, 36)
                                        .addComponent(unisex)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Address)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Email)
                                    .addComponent(Phone)
                                    .addComponent(Name)
                                    .addComponent(Roll, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(now)
                                        .addGap(18, 18, 18)
                                        .addComponent(unow))
                                    .addComponent(Class_Student, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(Roll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(Nam)
                    .addComponent(Nu)
                    .addComponent(unisex))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(Class_Student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(now)
                    .addComponent(unow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String regex_Phone = "^0[0-9]{9,10}$";
        int id = student.getId();
        String roll = Roll.getText();
        String name = Name.getText();
        String phone = Phone.getText();
        String mail = Email.getText();
        String addres = Address.getText();
        String birthday = new SimpleDateFormat("yyyy/MM/dd").format(DOB.getDate());
        int gen = 1;
        if (Nam.isSelected()) {
            gen = 1;
        } else if (Nu.isSelected()) {
            gen = 2;
        } else if (unisex.isSelected()) {
            gen = 3;
        }
        int class_choose = LClass.get(Class_Student.getSelectedIndex()).getId();
        int status;
        if (now.isSelected()) {
            status = 1;
        } else {
            status = 2;
        }
        if (name.length() == 0 || phone.length() == 0 || mail.length() == 0 || addres.length() == 0) {
            JOptionPane.showMessageDialog(null, "Bạn đã cập nhập thành công thông tin sinh viên");
        } else if (phone.length() > 11 || phone.length() < 10 || regex_Phone.matches(phone)) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đúng số điện thoại để tiếp tục");
        } else {
            tbl_Student student_edit = new tbl_Student(id, roll, name, phone, mail, addres, birthday, status, class_choose, "", gen);
            Student_Controller SC = new Student_Controller(conn);
            if (SC.update(student_edit)) {
                JOptionPane.showMessageDialog(null, "Bạn đã thay đổi thông tin học viên thành công!");
                load.load_table();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Đã có lỗi xảy ra");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JComboBox<String> Class_Student;
    private com.toedter.calendar.JDateChooser DOB;
    private javax.swing.JTextField Email;
    private javax.swing.JRadioButton Nam;
    private javax.swing.JTextField Name;
    private javax.swing.JRadioButton Nu;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Roll;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton now;
    private javax.swing.JRadioButton unisex;
    private javax.swing.JRadioButton unow;
    // End of variables declaration//GEN-END:variables
}
