/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Internal;

import App.controller.Student_Controller;
import App.model.tbl_Class;
import App.model.tbl_Student;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;


/**
 *
 * @author PC Hoang Anh
 */
public class View_Class_Student extends javax.swing.JInternalFrame {

    /**
     * Creates new form View_Class_Student
     */
    public interface View_Mark_Student {

        public void viewMark(tbl_Student s);
        
        public void viewStudent(tbl_Student s);
    };

    List<tbl_Student> LS;
    tbl_Class c;
    Connection conn;
    View_Mark_Student v;

    public View_Class_Student(tbl_Class c, Connection conn, View_Mark_Student v) {
        this.c = c;
        this.conn = conn;
        this.v = v;
        initComponents();
        jLabel.setText("Danh Sách Học Sinh Lớp " + c.getName());
        getStudent(" WHERE Class_ID = " + c.getId());
        loadTable();
    }
    public View_Class_Student(tbl_Class c, Connection conn) {
        this.c = c;
        this.conn = conn;
        initComponents();
        jLabel.setText("Danh Sách Học Sinh Lớp " + c.getName());
        getStudent(" WHERE Class_ID = " + c.getId());
        loadTable();
    }

    private void getStudent(String check) {
        Student_Controller SC = new Student_Controller(conn);
        LS = SC.select(check);
    }

    private void loadTable() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã SV");
        dtm.addColumn("Tên SV");
        dtm.addColumn("Email");
        dtm.addColumn("Địa chỉ");
        dtm.addColumn("Giới tính");
        dtm.addColumn("Ngày sinh");
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat dfS = new SimpleDateFormat("dd/MM/yyyy");
        for (tbl_Student s : LS) {
            String DOB = "";
            try {
                DOB = dfS.format(df.parse(s.getDOB()));
            } catch (ParseException ex) {
                Logger.getLogger(View_Info_Student.class.getName()).log(Level.SEVERE, null, ex);
            }
            switch (s.getGender()) {
                case 1: {
                    Object o[] = {
                        s.getRoll(), s.getName(), s.getEmail(), s.getAddress(), "Nam", DOB
                    };
                    dtm.addRow(o);
                    break;
                }
                case 2: {
                    Object o[] = {
                        s.getRoll(), s.getName(), s.getEmail(), s.getAddress(), "Nữ", DOB
                    };
                    dtm.addRow(o);
                    break;
                }
                default: {
                    Object o[] = {
                        s.getRoll(), s.getName(), s.getEmail(), s.getAddress(), "Chưa xác định", DOB
                    };
                    dtm.addRow(o);
                    break;
                }
            }
        }
        Table_Content.setModel(dtm);
        Table_Content.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Mark_View = new javax.swing.JMenuItem();
        View_Student = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Content = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        Mark_View.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Mark_View.setText("Xem điểm");
        Mark_View.setToolTipText("Xem và sửa điểm cho sinh viên");
        Mark_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mark_ViewActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Mark_View);

        View_Student.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        View_Student.setText("Xem Thông Tin Học Viên");
        View_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_StudentActionPerformed(evt);
            }
        });
        jPopupMenu1.add(View_Student);

        setClosable(true);
        setTitle("Danh sách sinh viên");

        jLabel.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("DANH SÁCH SINH VIÊN CỦA LỚP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel)
        );

        Table_Content.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Table_Content.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Content.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Table_ContentMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Content);

        jButton1.setText("In DS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mark_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mark_ViewActionPerformed
        tbl_Student s = LS.get(Table_Content.getSelectedRow());
        v.viewMark(s);
    }//GEN-LAST:event_Mark_ViewActionPerformed

    private void Table_ContentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ContentMousePressed
        jPopupMenu1.show(Table_Content, evt.getX(), evt.getY());
    }//GEN-LAST:event_Table_ContentMousePressed

    private void View_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_StudentActionPerformed
        tbl_Student s = LS.get(Table_Content.getSelectedRow());
        v.viewStudent(s);
    }//GEN-LAST:event_View_StudentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet = workbook.createSheet("danhsach");
        XSSFRow row = null;
        Cell cell = null;
        row = sheet.createRow(3);
        cell = row.createCell(0,CellType.STRING);
        cell.setCellValue("STT");
        
        cell = row.createCell(1,CellType.STRING);
        cell.setCellValue("MSSV");
        
        cell = row.createCell(2,CellType.STRING);
        cell.setCellValue("Họ tên");
        
        cell = row.createCell(3,CellType.STRING);
        cell.setCellValue("Ngày sinh");
        
        cell = row.createCell(4,CellType.STRING);
        cell.setCellValue("Giới tính");
        
        cell = row.createCell(5,CellType.STRING);
        cell.setCellValue("Email");
        
        cell = row.createCell(6,CellType.STRING);
        cell.setCellValue("Địa chỉ");
        
        for (int i=0; i<LS.size();i++)
        {
            row = sheet.createRow(4+i);
            
            cell = row.createCell(0,CellType.NUMERIC);
            cell.setCellValue(i+1);
            
            cell = row.createCell(1,CellType.STRING);
            cell.setCellValue(LS.get(i).getId());
            
            cell = row.createCell(2,CellType.STRING);
            cell.setCellValue(LS.get(i).getName());
            
            cell = row.createCell(3,CellType.STRING);
            cell.setCellValue(LS.get(i).getDOB());
            
            cell = row.createCell(4,CellType.STRING);
            cell.setCellValue(LS.get(i).getGender());
            
            cell = row.createCell(5,CellType.STRING);
            cell.setCellValue(LS.get(i).getEmail());
            
            cell = row.createCell(6,CellType.STRING);
            cell.setCellValue(LS.get(i).getAddress());
            
           
            
        }
         File f = new File("D://danhsach.xlsx");
            try {
                FileOutputStream fl = new FileOutputStream(f);
                workbook.write(fl);
                fl.close();
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
               ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "In thành công");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Mark_View;
    private javax.swing.JTable Table_Content;
    private javax.swing.JMenuItem View_Student;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
