/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.panel;

import App.Internal.View_Class_Student;
import App.Internal.View_Class_Student.View_Mark_Student;
import App.Internal.View_Info_Student;
import App.Internal.View_Mark;
import App.controller.Class_Controller;
import App.controller.Course_Controller;
import App.controller.Student_Controller;
import App.controller.Teacher_Controller;
import App.model.tbl_Class;
import App.model.tbl_Course;
import App.model.tbl_Student;
import App.model.tbl_Teacher;
import java.sql.Connection;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC Hoang Anh
 */
public class Panel_Class extends javax.swing.JPanel implements View_Mark_Student {

    /**
     * Creates new form Panel_Class
     */
    Connection conn;
    tbl_Teacher acc;
    List<tbl_Teacher> LT;
    List<tbl_Class> LC;
    List<tbl_Course> LCA;
    tbl_Class edit_class;

    public Panel_Class(Connection conn, tbl_Teacher acc) {
        this.conn = conn;
        this.acc = acc;
        initComponents();
        Save_Edit_Clas.setVisible(false);
        End_Edit_Clas.setVisible(false);
        getCourse();
        set_Cbx_Course();
        load_Teach();
        set_Cbx_Class_Teacher();
        if (acc.getRole_ID() == 1 || acc.getRole_ID() == 2) {
            load_Class_Table("");
        } else {
            load_Class_Table(" WHERE Teacher_ID = " + acc.getID());
        }
    }

    private void getCourse() {
        Course_Controller CC = new Course_Controller(conn);
        LCA = CC.select("");
    }

    private void load_Class_Table(String check) {
        Class_Controller CC = new Class_Controller(conn);
        if ((acc.getRole_ID() == 1 || acc.getRole_ID() == 2) && "".equals(check)) {
            LC = CC.select(check);
        } else {
            LC = CC.select(check);
        }
        DefaultTableModel DTM = new DefaultTableModel();
        DTM.addColumn("STT");
        DTM.addColumn("Tên lớp");
        DTM.addColumn("Khóa");
        DTM.addColumn("Số học sinh");
        DTM.addColumn("Giáo viên chủ nhiệm");
        Student_Controller SC = new Student_Controller(conn);
        for (int i = 0; i < LC.size(); i++) {
            tbl_Class c = LC.get(i);
            for (tbl_Teacher t : LT) {
                if (t.getID() == c.getTeacher_id()) {
                    for (tbl_Course course : LCA) {
                        if (course.getId() == c.getCourse_id()) {
                            Object o[] = {
                                (i + 1), c.getName(), course.getName(), SC.select(" WHERE Class_ID = " + c.getId()).size(), t.getName()
                            };
                            DTM.addRow(o);
                        }
                    }
                }
            }
        }
        Class_Table.setModel(DTM);
        Class_Table.setRowHeight(25);
    }

    private void load_Teach() {
        Teacher_Controller TC = new Teacher_Controller(conn);
        LT = TC.select(" WHERE Role_ID <> 2 AND Role_ID <> 4 AND Status = 1");
    }

    private void set_Cbx_Class_Teacher() {
        DefaultComboBoxModel DCM = new DefaultComboBoxModel();
        if (acc.getRole_ID() == 1 || acc.getRole_ID() == 2) {
            for (tbl_Teacher t : LT) {
                DCM.addElement(t.getName());
            }
        } else {
            DCM.addElement(acc.getName());
        }
        Cbx_Class_Teacher.setModel(DCM);
    }

    private void set_Cbx_Course() {
        DefaultComboBoxModel DCM = new DefaultComboBoxModel();
        for (tbl_Course c : LCA) {
            DCM.addElement(c.getName());
        }
        Cbx_Class.setModel(DCM);
        Cbx_Class_Course.setModel(DCM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Class_PopUp = new javax.swing.JPopupMenu();
        Edit_Class = new javax.swing.JMenuItem();
        View_Student = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Class_Search = new javax.swing.JTextField();
        Cbx_Class = new javax.swing.JComboBox<>();
        Search_Class = new javax.swing.JButton();
        Reload_Class = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Class_Table = new javax.swing.JTable();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Name_Class = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Cbx_Class_Course = new javax.swing.JComboBox<>();
        Cbx_Class_Teacher = new javax.swing.JComboBox<>();
        jPanel27 = new javax.swing.JPanel();
        Add_New_Class = new javax.swing.JButton();
        Refesh_add_Class = new javax.swing.JButton();
        End_Edit_Clas = new javax.swing.JButton();
        Save_Edit_Clas = new javax.swing.JButton();

        Edit_Class.setText("Sửa Thông Tin Lớp");
        Edit_Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_ClassActionPerformed(evt);
            }
        });
        Class_PopUp.add(Edit_Class);

        View_Student.setText("Xem Danh Sách Học Sinh");
        View_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_StudentActionPerformed(evt);
            }
        });
        Class_PopUp.add(View_Student);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setText("Tên Lớp:");

        Class_Search.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        Cbx_Class.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        Cbx_Class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Cbx_Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbx_ClassActionPerformed(evt);
            }
        });

        Search_Class.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        Search_Class.setText("Tìm");
        Search_Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ClassActionPerformed(evt);
            }
        });

        Reload_Class.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        Reload_Class.setText("Tải Lại DS");
        Reload_Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reload_ClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Class_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cbx_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reload_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Search_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cbx_Class)
                    .addComponent(Class_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reload_Class, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Class_Table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Class_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Class_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Class_TableMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(Class_Table);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thêm Lớp Học Mới", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("Tên Lớp:");

        Name_Class.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        Name_Class.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setText("Khóa Học:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Giảng Viên HD:");

        Cbx_Class_Course.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        Cbx_Class_Course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Cbx_Class_Teacher.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        Cbx_Class_Teacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cbx_Class_Teacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(Cbx_Class_Course, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addGap(10, 10, 10)
                .addComponent(Name_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cbx_Class_Course, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(Cbx_Class_Teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Add_New_Class.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Add_New_Class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/Button-Add-icon.png"))); // NOI18N
        Add_New_Class.setText("Thêm");
        Add_New_Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_New_ClassActionPerformed(evt);
            }
        });

        Refesh_add_Class.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Refesh_add_Class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/Reset-icon.png"))); // NOI18N
        Refesh_add_Class.setText("Nhập Lại");
        Refesh_add_Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refesh_add_ClassActionPerformed(evt);
            }
        });

        End_Edit_Clas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        End_Edit_Clas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/Button-Close-icon.png"))); // NOI18N
        End_Edit_Clas.setText("Hủy");
        End_Edit_Clas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                End_Edit_ClasActionPerformed(evt);
            }
        });

        Save_Edit_Clas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Save_Edit_Clas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/edit.png"))); // NOI18N
        Save_Edit_Clas.setText("Lưu");
        Save_Edit_Clas.setToolTipText("");
        Save_Edit_Clas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_Edit_ClasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(End_Edit_Clas, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Save_Edit_Clas, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(Refesh_add_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add_New_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Refesh_add_Class)
                    .addComponent(Add_New_Class))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save_Edit_Clas)
                    .addComponent(End_Edit_Clas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane.setLayer(jPanel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jDesktopPane)
                    .addGap(0, 0, 0)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jDesktopPane)
                    .addGap(0, 0, 0)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Cbx_ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbx_ClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cbx_ClassActionPerformed

    private void Search_ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ClassActionPerformed
        String seachr = Class_Search.getText();
        int course_id = LCA.get(Cbx_Class.getSelectedIndex()).getId();
        if (acc.getRole_ID() == 1 || acc.getRole_ID() == 2) {
            load_Class_Table("WHERE Name LIKE N'%" + seachr + "%' AND Course_ID = " + course_id);
        } else {
            load_Class_Table("WHERE Name LIKE N'%" + seachr + "%' AND Course_ID = " + course_id + " AND Teacher_ID = " + acc.getID());
        }
    }//GEN-LAST:event_Search_ClassActionPerformed

    private void Reload_ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reload_ClassActionPerformed
        if (acc.getRole_ID() == 1 || acc.getRole_ID() == 2) {
            load_Class_Table("");
        } else {
            load_Class_Table(" WHERE Teacher_ID = " + acc.getID());
        }
    }//GEN-LAST:event_Reload_ClassActionPerformed

    private void Class_TableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Class_TableMousePressed
        Class_PopUp.show(Class_Table, evt.getX(), evt.getY());
    }//GEN-LAST:event_Class_TableMousePressed

    private void Add_New_ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_ClassActionPerformed
        tbl_Class new_C;
        if (acc.getRole_ID() > 3) {
            JOptionPane.showMessageDialog(null, "Bạn không đủ quyền hạn để thực hiện");
        } else {
            if (acc.getRole_ID() == 2) {
                String name = Name_Class.getText();
                int Course_ID = LCA.get(Cbx_Class_Course.getSelectedIndex()).getId();
                new_C = new tbl_Class(name, Course_ID, acc.getID());
            } else {
                String name = Name_Class.getText();
                int Course_ID = LCA.get(Cbx_Class_Course.getSelectedIndex()).getId();
                int Teach_ID = LT.get(Cbx_Class_Teacher.getSelectedIndex()).getID();
                new_C = new tbl_Class(name, Course_ID, Teach_ID);
            }
            if (!"".equals(new_C.getName())) {
                Class_Controller CC = new Class_Controller(conn);
                if (CC.insert(new_C) == 1) {
                    JOptionPane.showMessageDialog(null, "Thành công");
                    Name_Class.setText("");
                    Cbx_Class_Course.setSelectedIndex(0);
                    Cbx_Class_Teacher.setSelectedIndex(0);
                } else {
                    JOptionPane.showMessageDialog(null, "Lỗi rồi");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Tên đang trống");
            }
        }
        if (acc.getRole_ID() == 1 || acc.getRole_ID() == 2) {
            load_Class_Table("");
        } else {
            load_Class_Table(" WHERE Teacher_ID = " + acc.getID());
        }
    }//GEN-LAST:event_Add_New_ClassActionPerformed

    private void Refesh_add_ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refesh_add_ClassActionPerformed
        Name_Class.setText("");
        Cbx_Class_Course.setSelectedIndex(0);
        Cbx_Class_Teacher.setSelectedIndex(0);
    }//GEN-LAST:event_Refesh_add_ClassActionPerformed

    private void End_Edit_ClasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_End_Edit_ClasActionPerformed
        edit_class = null;
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thêm Lớp Học Mới", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16)));
        Name_Class.setText("");
        Cbx_Class_Course.setSelectedIndex(0);
        Cbx_Class_Teacher.setSelectedIndex(0);
        Save_Edit_Clas.setVisible(false);
        End_Edit_Clas.setVisible(false);
        Add_New_Class.setVisible(true);
        Refesh_add_Class.setVisible(true);
    }//GEN-LAST:event_End_Edit_ClasActionPerformed

    private void Save_Edit_ClasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_Edit_ClasActionPerformed
        String name_Class_edit = Name_Class.getText();
        int Course_ID_Class_Edit = LCA.get(Cbx_Class_Course.getSelectedIndex()).getId();
        if (acc.getRole_ID() == 1 || acc.getRole_ID() == 2) {
            int Teacher_ID_Class_Edit = LT.get(Cbx_Class_Teacher.getSelectedIndex()).getID();
            edit_class.setTeacher_id(Teacher_ID_Class_Edit);
        }
        edit_class.setCourse_id(Course_ID_Class_Edit);
        if ("".equals(name_Class_edit)) {
            JOptionPane.showMessageDialog(null, "Tên lớp đang để trống");
        } else {
            edit_class.setName(name_Class_edit);
            Class_Controller CC = new Class_Controller(conn);
            if (CC.update(edit_class)) {
                JOptionPane.showMessageDialog(null, "Cập nhập dữ liệu thành công");
                edit_class = null;
                jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thêm Lớp Học Mới", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16)));
                Name_Class.setText("");
                Cbx_Class_Course.setSelectedIndex(0);
                if (acc.getRole_ID() == 1 || acc.getRole_ID() == 2) {
                    Cbx_Class_Teacher.setSelectedIndex(0);
                }
                Save_Edit_Clas.setVisible(false);
                End_Edit_Clas.setVisible(false);
                Add_New_Class.setVisible(true);
                Refesh_add_Class.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Lỗi rồi!");
            }
        }
        if (acc.getRole_ID() == 1 || acc.getRole_ID() == 2) {
            load_Class_Table("");
        } else {
            load_Class_Table(" WHERE Teacher_ID = " + acc.getID());
        }
    }//GEN-LAST:event_Save_Edit_ClasActionPerformed

    private void Edit_ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_ClassActionPerformed
        edit_class = LC.get(Class_Table.getSelectedRow());
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sửa Thông Tin Lớp Học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16)));
        Name_Class.setText(edit_class.getName());
        for (int i = 0; i < LCA.size(); i++) {
            tbl_Course c = LCA.get(i);
            if (c.getId() == edit_class.getCourse_id()) {
                Cbx_Class_Course.setSelectedIndex(i);
            }
        }
        Cbx_Class_Teacher.setSelectedIndex(0);
        Save_Edit_Clas.setVisible(true);
        End_Edit_Clas.setVisible(true);
        Add_New_Class.setVisible(false);
        Refesh_add_Class.setVisible(false);
    }//GEN-LAST:event_Edit_ClassActionPerformed

    private void View_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_StudentActionPerformed
        View_Class_Student VCS = new View_Class_Student(LC.get(Class_Table.getSelectedRow()), conn, this);
        jDesktopPane.add(VCS);
        VCS.setVisible(true);
    }//GEN-LAST:event_View_StudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_New_Class;
    private javax.swing.JComboBox<String> Cbx_Class;
    private javax.swing.JComboBox<String> Cbx_Class_Course;
    private javax.swing.JComboBox<String> Cbx_Class_Teacher;
    private javax.swing.JPopupMenu Class_PopUp;
    private javax.swing.JTextField Class_Search;
    private javax.swing.JTable Class_Table;
    private javax.swing.JMenuItem Edit_Class;
    private javax.swing.JButton End_Edit_Clas;
    private javax.swing.JTextField Name_Class;
    private javax.swing.JButton Refesh_add_Class;
    private javax.swing.JButton Reload_Class;
    private javax.swing.JButton Save_Edit_Clas;
    private javax.swing.JButton Search_Class;
    private javax.swing.JMenuItem View_Student;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void viewMark(tbl_Student s) {
        View_Mark vm = new View_Mark(conn, s);
        jDesktopPane.add(vm);
        vm.setVisible(true);
    }

    @Override
    public void viewStudent(tbl_Student s) {
        View_Info_Student VTS = new View_Info_Student(conn, s);
        jDesktopPane.add(VTS);
        VTS.setVisible(true);
    }
}
